name: deploy
on:
  push:
    branches: [master] # main 分支有 push 时触发
    paths-ignore:   # 下列文件的变更不触发部署，可以自行添加
      - README.md
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 下载源码
      - name: Checkout
        uses: actions/checkout@v4  # 使用最新版本

      # 设置Node.js环境
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'pnpm'  # 缓存pnpm依赖

      # 安装pnpm
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: latest

      # 安装依赖
      - name: Install dependencies
        run: pnpm install

      # 打包构建
      - name: Build
        run: pnpm run build

      # 部署到 GitHub pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4  # 使用最新版本
        with:
          branch: gh-pages
          publish_dir: ./dist
          github_token: ${{ secrets.CICDDEMO }}
          user_name: ${{ secrets.MY_USER_NAME }}
          user_email: ${{ secrets.MY_USER_EMAIL }}
          commit_message: 自动部署 ${{ github.sha }}  # 包含提交哈希，便于追溯
